language: node_js

node_js:
  - node

script:
  - make lint
  - make test-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=f22c3a697f7a5572b4f160690b3ac19e6814e0f612e62363e7f1e721cdb94a9e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
